name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build project
      uses: docker://cortesja/arm-none-eabi-scons:latest
      with:
        args: bash -c "scons"